projectName: This is test report
dataset:
  connection:
    connectionString: Data Source=powerbi://api.powerbi.com/v1.0/myorg/EMEA Development;Initial
      Catalog="EU Order to Cash (Ad-hoc)";Access Mode=readonly;Integrated Security=ClaimsToken
    database: 7f97f9b2-2c89-4359-966b-4612b960fbb1
  modelName: EU Order to Cash (Ad-Hoc)
report:
  title: {text: This is test report}
  data_refresh: {table: Date Refresh Table, column: UPDATED_DATE}
  measures:
  - {name: Billed_Units Measure, table: Order To Cash (OTC), expression: 'SUM( ''Order
      To Cash (OTC)''[Billed_Units] )', dataType: decimal number}
  visuals:
  - type: matrix
    position: {x: 28.8, y: 100, width: 1220, height: 800}
    rows:
    - {name: Payer Hierarchy Level 1 Label, table: Payer Customer (Hierarchy), type: Column}
    columns:
    - {name: Year, table: Order To Cash (OTC), type: Column}
    values:
    - {name: Billed_Units Measure, table: Order To Cash (OTC), type: Measure}
    filters:
    - {field: {name: Company ID, table: Country, type: column}, filterType: Categorical,
      values: [E211, E320, E667]}
    - {field: {name: Distribution Channel Code, table: Distribution Channel, type: column},
      filterType: Categorical, values: ['01']}
    - {field: {name: PAK Hierarchy Level 1 Code, table: Product Aggregation Key (PAK),
        type: column}, filterType: Categorical, values: ['10']}