projectName: 1.1.10.117. Daily Report Renault
dataset:
  connection:
    connectionString: Data Source=powerbi://api.powerbi.com/v1.0/myorg/EMEA Development;Initial
      Catalog="EU Order to Cash (Ad-hoc)";Access Mode=readonly;Integrated Security=ClaimsToken
    database: 7f97f9b2-2c89-4359-966b-4612b960fbb1
  modelName: EU Order to Cash (Ad-Hoc)
report:
  title: {text: 1.1.10.117. Daily Report Renault}
  data_refresh: {table: Date Refresh Table, column: UPDATED_DATE}
  measures:
  - {name: Current Year, table: Order To Cash (OTC), expression: 'SELECTEDVALUE(''Order
      To Cash (OTC)''[Year]) = YEAR(TODAY())', dataType: true/false}
  - {name: Current Month, table: Order To Cash (OTC), expression: 'SELECTEDVALUE(''Order
      To Cash (OTC)''[Month]) = Month(TODAY())', dataType: true/false}
  - {name: Billed_Units Measure, table: Order To Cash (OTC), expression: "SUM(\n \
      \   'Order To Cash (OTC)'[Billed_Units]\n)", dataType: decimal number}
  - {name: Order_Qty__Not_Cancelled_ Measure, table: Order To Cash (OTC), expression: "SUM(\n\
      \    'Order To Cash (OTC)'[Order_Qty(Not Cancelled)]\n)", dataType: whole number}
  - {name: Order_Qty__Prior_Working_Day_ Measure, table: Order To Cash (OTC), expression: 'SUM(''Order
      To Cash (OTC)''[Order_Qty(Prior Working Day)])', dataType: decimal number}
  visuals:
  - type: matrix
    position: {x: 28.8, y: 100, width: 1220, height: 400}
    rows:
    - {name: Sold To Hierarchy Level 5 Label, table: Sold To Customer (Hierarchy),
      type: Column}
    - {name: KAM Local Country ID, table: Selling Responsible, type: Column}
    - {name: PAK Hierarchy Level 2 Desc, table: Product Aggregation Key (PAK), type: Column}
    columns: []
    values:
    - {name: Billed_Units Measure, table: Order To Cash (OTC), type: Measure}
    - {name: Order_Qty__Not_Cancelled_ Measure, table: Order To Cash (OTC), type: Measure}
    - {name: Order_Qty__Prior_Working_Day_ Measure, table: Order To Cash (OTC), type: Measure}
    filters:
    - {field: {name: Company ID, table: Country, type: column}, filterType: Categorical,
      values: [E211]}
    - {field: {name: Distribution Channel Code, table: Distribution Channel, type: column},
      filterType: Categorical, values: ['01']}
    - {field: {name: PAK Hierarchy Level 1 Code, table: Product Aggregation Key (PAK),
        type: column}, filterType: Categorical, values: ['10']}
    - {field: {name: Year, table: Order To Cash (OTC), type: Column}, filterType: Categorical,
      values: [2025]}
    - {field: {name: Month, table: Order To Cash (OTC), type: Column}, filterType: Categorical,
      values: [6]}
    - {field: {name: Payer Hierarchy Level 4 ID, table: Payer Customer (Hierarchy),
        type: column}, filterType: Categorical, values: [DE4RENZENT]}